version: "3"

services:
  mailer-service:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "Kasemsak Kanunkhon"
      FROM_ADDRESS: kasemsak.Kanunkhon@example.com

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"

